version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      assignment-network:
        aliases:
          - mongodb_container
volumes:
  mongodb_data_container:

networks:
  assignment-network:
    driver: bridge