app:
  publicEndPoint: "http://localhost:8081"
  security:
    jwt:
      secret: "FqGtVS46UhA3Gfe79XYVrJQtbMkX6hn5TrkadzCZEmrjaV"
      #2 hours
      expiration-seconds: 7200
    pass-encoder:
      secret: mysecret
      iteration: 33
      key-length: 256